on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
jobs:
  poc:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{ toJSON(github.event) }}
      - run: echo ${{ toJSON(github.event.pull_request.labels.*.name) }}
      - run: echo ${{ contains(github.event.pull_request.labels.*.name, 'bug') }}
      - run: echo ${{ contains(github.event.pull_request.labels.*.name, 'missing-label') }}
      
